"""tabla alerts y contador de fallos

Revision ID: 10526bdd5c54
Revises: 52f83bbd0f4c
Create Date: 2026-07-13 14:14:45.510236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10526bdd5c54'
down_revision: Union[str, Sequence[str], None] = '52f83bbd0f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=12), server_default='critical', nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=12), server_default='active', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('metrics_time_idx'), table_name='metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('metrics_time_idx'), 'metrics', [sa.literal_column('time DESC')], unique=False)
    op.drop_column('devices', 'consecutive_failures')
    op.drop_table('alerts')
    # ### end Alembic commands ###
