"""tabla metrics y estado en devices

Revision ID: 52f83bbd0f4c
Revises: 608e364bd8d6
Create Date: 2026-07-10 18:55:06.564466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f83bbd0f4c'
down_revision: Union[str, Sequence[str], None] = '608e364bd8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'device_id', 'metric_key')
    )
    op.execute("SELECT create_hypertable('metrics', by_range('time'), if_not_exists => TRUE);")
    op.add_column('devices', sa.Column('status', sa.String(length=12), server_default='unknown', nullable=False))
    op.add_column('devices', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_seen_at')
    op.drop_column('devices', 'status')
    op.drop_table('metrics')
    # ### end Alembic commands ###
