"""agregar campos SNMP a devices

Revision ID: 608e364bd8d6
Revises: 39f44c4fb308
Create Date: 2026-07-06 15:41:13.706244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608e364bd8d6'
down_revision: Union[str, Sequence[str], None] = '39f44c4fb308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('snmp_version', sa.String(length=4), server_default='v2c', nullable=False))
    op.add_column('devices', sa.Column('snmp_community', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('snmp_port', sa.Integer(), server_default='161', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'snmp_port')
    op.drop_column('devices', 'snmp_community')
    op.drop_column('devices', 'snmp_version')
    # ### end Alembic commands ###
